---
schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  name: software-versions
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  charts:
    openstack:
      glance:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: glance
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      glance-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      heat:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: heat
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      heat-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      horizon:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: horizon
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      horizon-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      ingress:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: ingress
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      ingress-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      keystone:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: keystone
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      keystone-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      libvirt:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: libvirt
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      libvirt-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      mariadb:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: mariadb
        reference: 8dc986740c83487261efa6540f89d5dbea211f98
      mariadb-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      memcached:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: memcached
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      memcached-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      neutron:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: neutron
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      neutron-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      nova:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: nova
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      nova-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      openvswitch:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: openvswitch
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      openvswitch-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75
      rabbitmq:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: rabbitmq
        reference: a4fa9b761e2de14df588c1e37f3693174f15ad36
      rabbitmq-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: 9f921f23fb2df702981a0b3d33062ff607350f75

